### ISSUE TITLE
Conflict with Noxesium(?)

### ISSUE THREAD

**Issue by StrangeOne101** [fixyldev/ComponentViewer#6]
# Description

I get a crash when I install the mod onto an existing fabric modpack. I see Noxesium mentioned in the crashlog, so I am assuming it is a possible mixin conflict (but unsure)

# Crash

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-08-08 12:07:46
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'componentviewer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_315.method_41798()" because "options" is null
	at net.minecraft.class_7172.modifyReturnValue$cpl000$noxesium$overridePrioritizeChunkUpdates(class_7172.java:1050)
	at net.minecraft.class_7172.method_41753(class_7172.java:131)
	at dev.fixyl.componentviewer.config.type.AbstractConfig.getValue(AbstractConfig.java:46)
	at dev.fixyl.componentviewer.config.ConfigJson.getConfigValues(ConfigJson.java:52)
	at dev.fixyl.componentviewer.config.ConfigManager.writeConfigFile(ConfigManager.java:84)
	at dev.fixyl.componentviewer.config.ConfigManager.readConfigFile(ConfigManager.java:78)
	at dev.fixyl.componentviewer.config.ConfigManager.<init>(ConfigManager.java:51)
	at dev.fixyl.componentviewer.config.ConfigManager.getInstance(ConfigManager.java:56)
	at dev.fixyl.componentviewer.ComponentViewer.<clinit>(ComponentViewer.java:48)
	... 16 more
```

Full crash report is attached.

[crash-2024-08-08_12.07.46-client.txt](https://github.com/user-attachments/files/16536020/crash-2024-08-08_12.07.46-client.txt)

**Comment by fixyldev** [comment]
Thanks for your bug report! This issue should be resolved with the next release of "Noxesium".
